apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: bql4qvs0q-go
  janus-idp.io/tekton: bql4qvs0q-go
  backstage.io/kubernetes-id: bql4qvs0q-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bql4qvs0q-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
