apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: bql4qvs0q-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bql4qvs0q-go 
  name: bql4qvs0q-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: bql4qvs0q-go 
